---
- name: Disable Selinux
  hosts: localhost
  become: true
  tasks:
    - name: Disable Selinux
      shell:
        cmd: setenforce 0
        cmd: sed -i 's/SELINUX=enabled/SELINUX=disabled/' /etc/selinux/config
  
